name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: publish releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.22.0'
      - name: Build and Release
        run: make release
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Update latest Release
        run: |
          latest_release=$(gh release view latest --json tagName --jq .tagName) || true
          if [ -n "$latest_release" ]; then
            gh release delete latest -y || true
          fi
          gh release create latest -t "Latest release" --target ${{ github.ref }} --notes "This is the latest release."
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}